### ISSUE TITLE
2023 Reveiw

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-insomnia#4]
@LuchoTurtle please review this doc in light of the work you've been doing in https://github.com/dwyl/learn-api-design/issues/46 + https://github.com/dwyl/learn-api-design/pull/47 with a specific focus on:

+ [ ] Does `insomina` report and collect stats on the latency of the API requests 
+ [ ] Can/should we use the `cloud` (hosted) version of `insomnia` for our `API` ...
+ [ ] Update the docs as necessary

It looks like the pricing has gone up:
<img width="1400" alt="image" src="https://user-images.githubusercontent.com/194400/210335975-3d8df236-0d68-4778-a673-6d54f6b736cc.png">

<img width="1400" alt="image" src="https://user-images.githubusercontent.com/194400/210336144-9fb57bab-baf4-4a4f-81e1-268f91ca57ae.png">

Do we _need_ to use the paid version or can we just sync our files via `GitHub`? 
Please investigate this for us. If we end up having to pay for the `Team` version, that's fine if it's going to save us a decent amount of time. 🙏

**Comment by LuchoTurtle** [comment]
Having created the #5 , I'm going to try and answer the questions you asked here.

 > Does `insomnia` report and collect stats on the latency of the API requests?

Insomnia is only for designing and testing APIs.
There aren't any features for API monitoring, unfortunately. 
If there are, they aren't explicitly [stated in their documentation](https://docs.insomnia.rest/insomnia/get-started).

 > Can/should we use the cloud (hosted) version of insomnia for our API

I personally find the testing features of Insomnia lacking when compared with Postman.
I've written this in a `Limitations` section in #5 . Manual unit testing lacks basic features such as changing env variables.
Or even `{id}`s in `GET` operations dynamically. 

If you don’t mind losing the testing/automation features, Insomnia is a great simple REST client.
But compared with Postman's testing and automation features, it severely lags behind.
I feel like [Postman's pricing](https://www.postman.com/pricing/), when compared with [Insomnia's](https://insomnia.rest/pricing), is not outrageous.

I feel Postman's testing featurettes [is more complete](https://www.postman.com/use-cases/api-testing-automation/) and, even though stress testing with Postman only [outputs sequential processes](https://stackoverflow.com/questions/36157105/postman-how-to-make-multiple-requests-at-the-same-time), you can easily use [Locust](https://locust.io/) (which is free) to handle stress testing.

> Do we need to use the paid version or can we just sync our files via GitHub?

We can sync our files via Github.
